# Generated by Django 5.0.1 on 2024-01-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='placeholder text'),
            preserve_default=False,
        ),
    ]
