# Generated by Django 4.2.9 on 2024-01-03 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojos_ninjas_app', '0002_dojo_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojo',
            name='desc',
        ),
    ]
