# Generated by Django 5.0.1 on 2024-01-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_show_created_at_show_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='desc',
            field=models.TextField(default='N/A'),
        ),
    ]
